INSERT INTO public.commodity_category (id, name) VALUES (1, 'Unknown');
INSERT INTO public.commodity_category (id, name) VALUES (2, 'Consumer Items');
INSERT INTO public.commodity_category (id, name) VALUES (3, 'Medicines');
INSERT INTO public.commodity_category (id, name) VALUES (4, 'Salvage');
INSERT INTO public.commodity_category (id, name) VALUES (5, 'Technology');
INSERT INTO public.commodity_category (id, name) VALUES (6, 'Foods');
INSERT INTO public.commodity_category (id, name) VALUES (7, 'Metals');
INSERT INTO public.commodity_category (id, name) VALUES (8, 'Chemicals');
INSERT INTO public.commodity_category (id, name) VALUES (9, 'Legal Drugs');
INSERT INTO public.commodity_category (id, name) VALUES (10, 'Weapons');
INSERT INTO public.commodity_category (id, name) VALUES (11, 'Industrial Materials');
INSERT INTO public.commodity_category (id, name) VALUES (12, 'Minerals');
INSERT INTO public.commodity_category (id, name) VALUES (13, 'Machinery');
INSERT INTO public.commodity_category (id, name) VALUES (14, 'Textiles');
INSERT INTO public.commodity_category (id, name) VALUES (15, 'Slavery');
INSERT INTO public.commodity_category (id, name) VALUES (16, 'Waste');
INSERT INTO public.commodity_category (id, name) VALUES (17, 'NonMarketable');
