CREATE TABLE allegiance (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_allegiance PRIMARY KEY (id)
);

CREATE TABLE faction (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name              VARCHAR(255)                            NOT NULL,
    allegiance_id     BIGINT                                  NOT NULL,
    government_id     BIGINT                                  NOT NULL,
    is_player_faction BOOLEAN                                 NOT NULL,
        CONSTRAINT pk_faction PRIMARY KEY (id)
);

CREATE TABLE faction_state (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    faction_id BIGINT,
    state_id   BIGINT,
    CONSTRAINT pk_faction_state PRIMARY KEY (id)
);

CREATE TABLE government (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_government PRIMARY KEY (id)
);

CREATE TABLE state (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_state PRIMARY KEY (id)
);

CREATE TABLE station_service (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_station_service PRIMARY KEY (id)
);

CREATE TABLE station_station_services (
    station_id          BIGINT NOT NULL,
    station_services_id BIGINT NOT NULL,
    CONSTRAINT pk_station_station_services PRIMARY KEY (station_id, station_services_id)
);

CREATE TABLE station_type (
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    type   VARCHAR(255),
    large  BIGINT                                  NOT NULL,
    medium BIGINT                                  NOT NULL,
    small  BIGINT                                  NOT NULL,
    CONSTRAINT pk_station_type PRIMARY KEY (id)
);

ALTER TABLE station
    ADD station_type_id BIGINT;

ALTER TABLE system
    ADD x DOUBLE PRECISION;

ALTER TABLE system
    ADD y DOUBLE PRECISION;

ALTER TABLE system
    ADD z DOUBLE PRECISION;

ALTER TABLE faction
    ADD CONSTRAINT uc_faction_name UNIQUE (name);

ALTER TABLE state
    ADD CONSTRAINT uc_state_name UNIQUE (name);

ALTER TABLE station_service
    ADD CONSTRAINT uc_station_service_name UNIQUE (name);

ALTER TABLE faction
    ADD CONSTRAINT FK_FACTION_ON_ALLEGIANCE FOREIGN KEY (allegiance_id)
        REFERENCES allegiance(id);

ALTER TABLE faction
    ADD CONSTRAINT FK_FACTION_ON_GOVERNMENT FOREIGN KEY (government_id)
        REFERENCES government(id);

ALTER TABLE faction_state
    ADD CONSTRAINT FK_FACTION_STATE_ON_FACTION FOREIGN KEY (faction_id)
        REFERENCES faction(id);

ALTER TABLE faction_state
    ADD CONSTRAINT FK_FACTION_STATE_ON_STATE FOREIGN KEY (state_id)
        REFERENCES state(id);

ALTER TABLE station
    ADD CONSTRAINT FK_STATION_ON_STATION_TYPE FOREIGN KEY (station_type_id)
        REFERENCES station_type(id);

ALTER TABLE station_station_services
    ADD CONSTRAINT fk_stastaser_on_station FOREIGN KEY (station_id)
        REFERENCES station(id);

ALTER TABLE station_station_services
    ADD CONSTRAINT fk_stastaser_on_station_service FOREIGN KEY (station_services_id)
        REFERENCES station_service(id);
