version: '3.9'

name: "edcm"

services:
  database:
    image: postgres:15.2-alpine3.17
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    user: postgres
    volumes:
      - edcm-postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend
    container_name: database
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 10

  flyway:
    image: flyway/flyway:9.15.2-alpine
    environment:
      - DB_URL
      - DB_USER
      - DB_PASSWORD
    command: -configFiles="/flyway/conf/flyway.conf" migrate
    volumes:
      - ../backend/src/main/resources/db/migration:/flyway/sql
      - ./flyway.config:/flyway/conf/flyway.conf
    depends_on:
      database:
        condition: service_healthy
    networks:
      - backend

  backend:
    image: vantys/backend:latest
    environment:
      - DB_URL
      - DB_USER
      - DB_PASSWORD
      - FLYWAY_ENABLED
    depends_on:
      database:
        condition: service_healthy
      flyway:
        condition: service_completed_successfully
    ports:
      - "8080:8080"
    networks:
      - backend
    container_name: backend
    restart: unless-stopped

networks:
  backend:

volumes:
  edcm-postgres-data:
    driver: local
