version: '3.9'

services:
  database:
    image: postgres:15.2-alpine3.17
    env_file:
      - env/db.env
    user: postgres
    volumes:
      - edcm-postgres-data:/var/lib/postgresql/data
      - .:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - backend
    container_name: database
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: ../backend/
      dockerfile: Dockerfile
    env_file:
      - env/backend.env
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - backend
    container_name: backend
    restart: unless-stopped

networks:
  backend:

volumes:
  edcm-postgres-data:
