spring:
  codec:
    max-in-memory-size: "500MB"
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  devtools:
    livereload:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    generate-ddl: true
    open-in-view: false
    show-sql: false
  flyway:
    enabled: ${FLYWAY_ENABLED}
    url: jdbc:postgresql://localhost:5432/postgres
    user: postgres
    password: postgres
    schemas: public
    create-schemas: true
management:
  server:
    port: 8080
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
    enabled-by-default: true
logging:
  level:
    com.edcm: DEBUG
integrations:
  github-commodities-url: https://raw.githubusercontent.com/RemainNA/cargo-manifest/main/items.json
  eddb:
    eddb-url: https://eddb.io/
    factions-path: archive/v6/factions.json
    commodities-path: archive/v6/commodities.json
zeromq:
  eddn-channel-url: tcp://eddn.edcd.io:9500:9500
  timeout: 600000
scheduled:
  github:
    cron: "0 0 */12 * * ?"
  eddb:
    factions:
      cron: "0 0 1 * * FRI"
